version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            export CIRCLE_PROJECT_REPONAME=sleekform
            git config --global user.email "mohithgm@gmail.com"
            git config --global user.name "mohithg"
            echo "machine github.com login mohithg password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=mohithg npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website
          filters:
            branches:
              only:
                - master
